package webapp.Utils;

public enum Constants {

    //сервисы
    USERS_SERVICE,
    TIMETABLES_SERVICE,
    NOTES_SERVICE,
    TASKS_SERVICE,
    PERIODS_SERVICE,
    EVENTS_SERVICE,

    //для сервлетов
    SESSION_USER,
    CHOSEN_TIMETABLES,
    EMAIL_VALIDATOR,
    PASSWORD_VALIDATOR,
    PASSWORD_ENCRYPTOR,
    NICKNAME_VALIDATOR,
    A,
    FORM_NAME,
    ACTION_ADD,
    ACTION_CHANGE,
    ACTION_DELETE,

    READ_ONLY,
    GREY,
    IS_FOUND,

    DATE_FORMAT,
    HTML_DATE_FORMAT,
    HTML_TIME_FORMAT,


    DEFAULT_OPTION_VALUE,
    SUCCESS_MESSAGE_NAME,
    ERROR_MESSAGE_NAME,


}
